### ISSUE TITLE
getDataByStation not working - Remote server error

### ISSUE THREAD

**Issue by SJang1** [k0deh0lic/metroLib#1]
아래대로 작성하여 테스트해보았습니다.
```php
$ml = NXLogisMetro\metroLib::getInstance();
$trainList = $ml->getDataByStation('1701', '1');
```
또한, metroLib에서 TOPIS API는 꺼두었습니다.
```php
private const USE_TOPIS_API = false;
```

응답값이 NULL이며 그에 따라 `PHP Fatal error:  Uncaught RuntimeException: Remote server error.` 발생합니다.
발생위치 : `metroLib.php on line 127`
해당 역 및 +-4역에 열차가 있는 상태임을 확인하였습니다.

getDataByLine에서는 문제가 없습니다.

**Comment by k0deh0lic** [comment]
Argument 순서가 반대로 되어 있네요. getDataByStation(string $line_code, string $station_code)로 정의되어 있으므로 아래와 같이 작성하셔야 올바르게 동작합니다.   
`
$ml->getDataByStation('1', '1701');
`


그러고보니 Example이 잘못되어 있네요. 수정하겠습니다.
