### ISSUE TITLE
동일한 열차가 중복으로 뜨는 현상

### ISSUE THREAD

**Issue by sgweb36511** [k0deh0lic/metroLib#10]
예를들어서 행선지, 현재 역까지 다 똑같은 K453과 S453이 같은 결과에 동시에 존재합니다.
보정이 필요할 것 같습니다.

**Comment by k0deh0lic** [comment]
해당 현상이 제 환경에서 재현되지 않습니다. 해당 현상이 발생할 때의 데이터를 주셔야 제가 보정 코드를 추가할 수 있습니다.

**Comment by sgweb36511** [comment]
`<?php
//라이브러리 불러오기
require_once('metroLib.php');
$ml = NXLogisMetro\metroLib::getInstance();
$trainList = $ml->getDataByLine('1');

//중복확인
$origin = [];
$trainY = false;
foreach($trainList as $e){
    foreach($origin as $ee){
        if(preg_replace("/[^0-9]*/s", "", $ee) == preg_replace("/[^0-9]*/s", "", $e["trn_no"])){
            $trainY = array($ee, $e["trn_no"]);
        }
    }
    $origin[] = $e["trn_no"];
}

//중복된 열차가 있을때
if($trainY){
    echo "중복된 열차가 있습니다:<br>";
    var_dump($trainY);
}
?>`
중복된 열차가 있는지 여부를 확인하는 코드인데요.
몇번만 돌려보면 바로 나오는 것을 볼수 있습니다.
예시)
중복된 열차가 있습니다:
array(2) { [0]=> string(5) "S0142" [1]=> string(5) "K0142" }

**Comment by k0deh0lic** [comment]
> Duplicate train data found! S0154 - K0154
RAW:
array (size=10)
  'trn_no' => string 'K0154' (length=5)
  'line' => string '1' (length=1)
  'trn_dir' => string 'U' (length=1)
  'trn_form_no' => null
  'trn_sts' => int 3
  'is_exp' => boolean false
  'stn_nm' => string '청량리' (length=9)
  'stn_cd' => string '0158' (length=4)
  'dst_stn_nm' => null
  'dst_stn_cd' => null
array (size=10)
  'trn_no' => string 'S0154' (length=5)
  'line' => string '1' (length=1)
  'trn_dir' => string 'U' (length=1)
  'trn_form_no' => string '108' (length=3)
  'trn_sts' => int 4
  'is_exp' => boolean false
  'stn_nm' => string '청량리' (length=9)
  'stn_cd' => string '0158' (length=4)
  'dst_stn_nm' => string '양주' (length=6)
  'dst_stn_cd' => string '1909' (length=4)

찾아보니 1호선 데이터에 문제가 있긴 하네요.   
찾아보니 전동 154열차는 서울교통공사 열차고, 잘못된 값은 모두 종착역, 조성정보 값이 null인 공통점을 찾아냈습니다.   
해당 사항을 패치하였습니다. 이슈 등록에 감사드립니다.
