### ISSUE TITLE
7호선 석남연장구간 조회 관련 문제

### ISSUE THREAD

**Issue by k0deh0lic** [k0deh0lic/metroLib#2]
7호선 석남연장구간 조회 관련 문제가 있음.

1. 7호선 석남행 열차가 부평구청행으로 표시되는 문제가 있음.
2. 7호선 석남역, 신곡역 역별 운행조회가 안됨.

이는 서울교통공사 쪽 전산이 완전히 반영되지 않아 발생하는 문제로 보임.
일단 역명 및 코드는 추가했고, 추후 전산에 완전히 반영되면 close 처리.

**Comment by saroro1** [comment]
현재 석남, 산곡역에 있는 상행 열차는 부종운, 까치울에 있다고 표시가 되긴 합니다

**Comment by k0deh0lic** [comment]
일단 석남행 열차가 부평구청행으로 뜨는 문제는 TOPIS 보정기능을 통해 해결할 수 있도록 조치하였습니다.
https://github.com/k0deh0lic/metroLib/commit/4b3108800d8e7d849e2c87a595ba8de2f870b6de

**Comment by k0deh0lic** [comment]
서울교통공사 측에서 7호선(석남-부평구청, 이하 석남선) 구간은 인천교통공사 관할이라 열차정보를 제공하지 않는다고 합니다.   
그러므로 석남선 구간의 역(석남, 산곡)은 역명으로 운행조회가 불가능합니다.   
또한 TOPIS 측에서도 석남선 구간의 정보를 제공하지 않아 석남선 구간을 운행중인 열차는 조회가 불가능합니다.   
metroLib 사용 시 참고 바랍니다.

**Comment by k0deh0lic** [comment]
2021년 12월 29일 기준으로 석남선 구간이 조회되고 있음을 확인함.
