### ISSUE TITLE
1호선에 탕정역이  null이 되는 현상

### ISSUE THREAD

**Issue by saroro1** [k0deh0lic/metroLib#3]
현재 탕정역은 전산상 존재하나 역명 및 역코드가 존재하지 않아 역 위치(stationNm)가 null이 되고 있습니다.
  null이면 탕정역에 있다고 보시면 될거 같습니다.

**Comment by k0deh0lic** [comment]
제 환경에서는 재현되지 않습니다. 혹시 예전 코드를 사용하고 계시다면 최신 코드로 업데이트하시기 바랍니다.

**Comment by saroro1** [comment]
`        {
            "trainY": "K0089",
            "trainP": "311B99",
            "sts": 2,
            "dir": 2,
            "line": "1",
            "stationCd": null,
            "stationNm": "소요산",
            "statnTnm": "인천",
            "directAt": "0",
            "lineGbn": 0
        },
        {
            "trainY": "K0637",
            "trainP": "311B77",
            "sts": 1,
            "dir": 2,
            "line": "1",
            "stationCd": null,
            "stationNm": null,
            "statnTnm": "신창",
            "directAt": "0",
            "lineGbn": 0
        },`


위는 정보제공처에서 제공하는 json의 일부입니다. K637 보시면 stationCd 및 stationNm이 null인 이유가
 탕정역 때문에 그렇습니다.

**Comment by k0deh0lic** [comment]
자료를 제공해주셔서 감사합니다. 근시일 내로 확인하고 대책을 마련하겠습니다.

**Comment by saroro1** [comment]
저같은 경우는 1호선이고 null일때 열차가 탕정역에 있다고 가정했습니다

**Comment by k0deh0lic** [comment]
수정했습니다. 제보 감사드립니다.

**Comment by k0deh0lic** [comment]
2021년 12월 29일 기준 탕정역이 제대로 조회되고 있으므로 관련 코드를 삭제했습니다.
