### ISSUE TITLE
2호선 순환 및 성수행에 대해

### ISSUE THREAD

**Issue by saroro1** [k0deh0lic/metroLib#5]
서울교통정보과(topis)에서 제공하는 api에서 2호선에 관련 내용입니다

2호선을 호출했을시 열번의 앞자리가 6이면 성수에서 운행을 마치고 기지로 입고합니다.

혹시 반영이 가능하신지 여쭤보고 싶습니다

PR 원하시면 내일 오후쯤에 해보겠습니다

**Comment by k0deh0lic** [comment]
확인했습니다. PR 감사드립니다.
