### ISSUE TITLE
5-8

### ISSUE THREAD

**Issue by sgweb36511** [k0deh0lic/metroLib#8]
머릿글자가 SMRT가 아니라 그냥 S아닌가요?
예) SMRT7102(X) S7102(O)

**Comment by k0deh0lic** [comment]
서울교통공사에서 제공하는 시각표 파일을 보니 5-8호선의 열차번호에는 어떠한 접두어도 붙이지 않네요.   
SMRT 접두어는 편의상 붙인 것이니 필요하면 S로 수정하든 붙이지 말든 알아서 하시면 되겠습니다.
